name: ybx comliper

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install yacc lex
      run: sudo apt-get install yacc lex -y
    - name: make
      run: make
    - run: echo success!
    - name: ybx execute
      run: ybx
